### ISSUE TITLE
Where can I download to the client

### ISSUE THREAD

**Issue by handeslfy** [muayad-mahmoud/Wonderland-Online-Private-Server#1]
Where can I download to the client

**Comment by muayad-mahmoud** [comment]
i was using WLORB client

**Comment by handeslfy** [comment]
I can't find it can you give me a download link? Thanks

**Comment by muayad-mahmoud** [comment]
Link for client is added to readme , that is the client i was using 
Also i added a note for userLimit in case you're having troubles logging in

Closed
